import React, { useEffect, useState } from "react";
import { Play, RefreshCw } from "lucide-react";
import { api } from "../../lib/api";

export default function AdminScraper() {
  const [items, setItems] = useState([]); const [queue,setQueue]=useState([]);
  const [running, setRunning] = useState(false); const [msg, setMsg] = useState(null);
  async function load() { const d = await api.get("/api/admin/scrape/runs"); setItems(d.items || []); const q=await api.get('/api/admin/scrape/queue?status=all'); setQueue(q.items||[]); }
  useEffect(() => { load().catch(() => {}); }, []);
  async function runDry() { setRunning(true); setMsg(null); try { const r = await api.post("/api/admin/scrape/run-dry", {}); setMsg(`Dry-run ${r.run_id?.slice(0,8)} ${r.status}`); await load(); } catch (e) { setMsg(`Dry-run failed: ${e.message}`);} finally {setRunning(false);} }
  const act=async(id,a)=>{try{const r=await api.post(`/api/admin/scrape/items/${id}/${a}`,{notes:'admin review'}); setMsg(`${a}: ${JSON.stringify(r)}`);}catch(e){const fields=e?.detail?.unverified_fields||[]; setMsg(fields.length?`Promote blocked. Verify: ${fields.join(", ")}`:`${a} failed: ${e.message}`);} await load();};
  const fieldAct=async(id,f,a,val)=>{try{const r=await api.post(`/api/admin/scrape/items/${id}/fields/${f}/${a}`,{notes:'field review', corrected_value:val}); setMsg(`${f} ${a}: ${JSON.stringify(r)}`); await load();}catch(e){setMsg(`${f} ${a} failed: ${e.message}`);} };

  return (<div className="space-y-6" data-testid="admin-scraper"><div className="flex items-start justify-between flex-wrap gap-3"><div><h1 className="mt-1 font-heading text-3xl font-semibold tracking-tight">Scrape queue trust review</h1><p className="text-muted-foreground mt-1">Promote creates draft/needs_review, it does not publish.</p></div><div className="flex gap-2"><button onClick={load} className="btn btn-ghost"><RefreshCw className="h-4 w-4" /> Reload</button><button disabled={running} onClick={runDry} className="btn btn-primary"><Play className={`h-4 w-4 ${running ? "animate-spin" : ""}`} />{running ? "Running…" : "Run dry-scrape"}</button></div></div>
  {msg && <div className="soft-card p-2 text-xs">{msg}</div>}
  <div className='soft-card rounded-2xl overflow-auto'><table className='w-full text-xs'><thead><tr>{['source','title','org_guess','dates','signals','status','actions'].map(h=><th key={h} className='text-left px-2 py-2'>{h}</th>)}</tr></thead><tbody>{queue.map(q=>{const e=q.extracted_data||{}; const blocked=(q.unverified_fields||[]); return <tr key={q.id} className='border-t align-top'><td className='px-2 py-2'><div className='font-medium'>{q.source_name}</div><div className='text-[10px] text-muted-foreground break-all'>{q.source_url}</div></td><td className='px-2 py-2'>{e.title||e.name||'—'}</td><td className='px-2 py-2'>{e.organization||'—'}</td><td className='px-2 py-2'>{e.apply_start_date||'—'}→{e.apply_end_date||'—'}</td><td className='px-2 py-2'><div>conf {q.confidence_score??'—'} · quality {q.data_quality_score??'—'}</div><div className='text-[10px] text-muted-foreground'>extract {q.extraction_status||'—'} · source {String(!!q.official_source_resolved)}</div>{blocked.length>0 && <div className='text-[10px] text-amber-700 mt-1'>Unverified: {blocked.join(', ')}</div>}</td><td className='px-2 py-2'>{q.status}</td><td className='px-2 py-2'><div className='flex flex-wrap gap-1'><button className='btn btn-ghost' onClick={()=>act(q.id,'approve')}>Approve</button><button className='btn btn-ghost' onClick={()=>act(q.id,'reject')}>Reject</button><button className='btn btn-primary' disabled={!q.promotable} title={blocked.length?`Verify: ${blocked.join(', ')}`:''} onClick={()=>act(q.id,'promote')}>Promote</button></div><details className='mt-1'><summary>Evidence actions</summary><pre className='max-w-[340px] overflow-auto'>{JSON.stringify(q.field_evidence_status||q.field_evidence||{},null,2)}</pre>{['title','organization_name','notification_date','apply_start_date','apply_end_date','total_vacancies','official_notification_url','official_apply_url'].map(f=><div key={f} className='text-[10px] border-t mt-1 pt-1'><b>{f}</b>: {String(e[f]??'—')} <button className='btn btn-ghost' onClick={()=>fieldAct(q.id,f,'verify')}>verify</button><button className='btn btn-ghost' onClick={()=>fieldAct(q.id,f,'reject')}>reject</button><button className='btn btn-ghost' onClick={()=>fieldAct(q.id,f,'correct', prompt('Correct value')||'')}>correct</button></div>)}</details></td></tr>})}</tbody></table></div></div>);
}
