import React, { useEffect, useState } from "react";
import { Play, RefreshCw } from "lucide-react";
import { api } from "../../lib/api";

export default function AdminScraper() {
  const [items, setItems] = useState([]); const [queue,setQueue]=useState([]);
  const [running, setRunning] = useState(false); const [msg, setMsg] = useState(null);
  async function load() { const d = await api.get("/api/admin/scrape/runs"); setItems(d.items || []); const q=await api.get('/api/admin/scrape/queue?status=all'); setQueue(q.items||[]); }
  useEffect(() => { load().catch(() => {}); }, []);
  async function runDry() { setRunning(true); setMsg(null); try { const r = await api.post("/api/admin/scrape/run-dry", {}); setMsg(`Dry-run ${r.run_id?.slice(0,8)} ${r.status}`); await load(); } catch (e) { setMsg(`Dry-run failed: ${e.message}`);} finally {setRunning(false);} }
  const act=async(id,a)=>{try{const r=await api.post(`/api/admin/scrape/items/${id}/${a}`,{notes:'admin review'}); setMsg(`${a}: ${JSON.stringify(r)}`);}catch(e){setMsg(`${a} failed: ${e.message}`);} await load();};

  return (<div className="space-y-6" data-testid="admin-scraper"><div className="flex items-start justify-between flex-wrap gap-3"><div><h1 className="mt-1 font-heading text-3xl font-semibold tracking-tight">Scrape queue trust review</h1><p className="text-muted-foreground mt-1">Promote creates draft/needs_review, it does not publish.</p></div><div className="flex gap-2"><button onClick={load} className="btn btn-ghost"><RefreshCw className="h-4 w-4" /> Reload</button><button disabled={running} onClick={runDry} className="btn btn-primary"><Play className={`h-4 w-4 ${running ? "animate-spin" : ""}`} />{running ? "Running…" : "Run dry-scrape"}</button></div></div>
  {msg && <div className="soft-card p-2 text-xs">{msg}</div>}
  <div className='soft-card rounded-2xl overflow-auto'><table className='w-full text-xs'><thead><tr>{['source','url','title','org_guess','dates','official_resolved','host','conf','quality','extract','evidence_req','duplicate','review_notes','status','actions'].map(h=><th key={h} className='text-left px-2 py-2'>{h}</th>)}</tr></thead><tbody>{queue.map(q=>{const e=q.extracted_data||{}; return <tr key={q.id} className='border-t'><td>{q.source_name}</td><td>{q.source_url}</td><td>{e.title||e.name||'—'}</td><td>{e.organization||'—'}</td><td>{e.apply_start_date||'—'}→{e.apply_end_date||'—'}</td><td>{String(!!q.official_source_resolved)}</td><td>{q.official_source_host||'—'}</td><td>{q.confidence_score??'—'}</td><td>{q.data_quality_score??'—'}</td><td>{q.extraction_status||'—'}</td><td>{String(!!q.evidence_required)}</td><td>{q.duplicate_of||'—'}</td><td>{q.reviewer_notes||'—'}</td><td>{q.status}</td><td><button className='btn btn-ghost' onClick={()=>act(q.id,'approve')}>Approve</button><button className='btn btn-ghost' onClick={()=>act(q.id,'reject')}>Reject</button><button className='btn btn-primary' onClick={()=>act(q.id,'promote')}>Promote</button><details><summary>Evidence</summary><pre className='max-w-[340px] overflow-auto'>{JSON.stringify(q.field_evidence||{},null,2)}</pre><div className='text-[10px]'>{(q.raw_html||'').slice(0,200)}</div></details></td></tr>})}</tbody></table></div></div>);
}
