-- Test seed: Free Job Alert as a discovery aggregator.
-- source_registry is the canonical source-management table. Do not seed
-- scrape_sources from this file; runner migration to source_registry should be
-- handled in application code, not by duplicating source ownership.

insert into public.source_registry (
  id,
  source_name,
  short_code,
  source_type,
  category,
  jurisdiction,
  official_url,
  notification_url,
  adapter_type,
  parser_config,
  scrape_interval_hours,
  tier,
  trust_score,
  anti_bot_risk,
  requires_playwright,
  requires_login,
  has_captcha,
  pdf_only,
  is_active,
  is_verified,
  notes,
  added_by,
  org_state,
  insecure_tls,
  requires_official_confirmation,
  is_official_source,
  can_publish_directly,
  discovery_only,
  verification_status,
  source_url
)
values (
  'a1d37c75-0e3c-4176-be3e-5f79755d2a60',
  'Free Job Alert',
  'FREE_JOB_ALERT',
  'aggregator',
  'central_govt',
  'central',
  'https://www.freejobalert.com',
  'https://www.freejobalert.com/government-jobs/',
  'html',
  '{"_seed":{"source":"Workbook1.xlsx","home_url":"https://www.freejobalert.com","authoritative_workbook":true}}'::jsonb,
  12,
  3,
  0.45,
  'low',
  false,
  false,
  false,
  false,
  true,
  false,
  'Aggregator seed. Requires official confirmation before promotion/publication.',
  'migration_004',
  null,
  false,
  true,
  false,
  false,
  true,
  'needs_review',
  'https://www.freejobalert.com/government-jobs/'
)
on conflict (id) do update set
  source_name = excluded.source_name,
  short_code = excluded.short_code,
  source_type = excluded.source_type,
  category = excluded.category,
  jurisdiction = excluded.jurisdiction,
  official_url = excluded.official_url,
  notification_url = excluded.notification_url,
  adapter_type = excluded.adapter_type,
  parser_config = excluded.parser_config,
  scrape_interval_hours = excluded.scrape_interval_hours,
  tier = excluded.tier,
  trust_score = excluded.trust_score,
  anti_bot_risk = excluded.anti_bot_risk,
  requires_playwright = excluded.requires_playwright,
  requires_login = excluded.requires_login,
  has_captcha = excluded.has_captcha,
  pdf_only = excluded.pdf_only,
  is_active = excluded.is_active,
  is_verified = excluded.is_verified,
  notes = excluded.notes,
  added_by = excluded.added_by,
  org_state = excluded.org_state,
  insecure_tls = excluded.insecure_tls,
  requires_official_confirmation = true,
  is_official_source = false,
  can_publish_directly = false,
  discovery_only = true,
  verification_status = excluded.verification_status,
  source_url = excluded.source_url,
  updated_at = now();
