import os

import pytest

from app.db.supabase_client import get_supabase_admin


REQUIRED_COLUMNS = {
    "profiles": {
        "id",
        "full_name",
        "phone",
        "gender",
        "category",
        "pwbd_status",
        "domicile_state",
        "nationality",
        "ex_serviceman",
        "govt_employee",
        "dob",
        "date_of_birth",
        "service_years",
        "graduation_year",
        "target_type",
        "target_exam",
        "career_stage",
        "career_goal",
        "onboarding_step",
        "onboarding_completed",
        "is_admin",
        "is_instructor",
        "instructor_bio",
        "plan_id",
        "avatar_url",
    },
    "recruitments": {
        "id",
        "organization_id",
        "slug",
        "name",
        "year",
        "status",
        "publish_status",
        "notification_date",
        "apply_start_date",
        "apply_end_date",
        "total_vacancies",
        "official_notification_url",
        "official_apply_url",
        "source_pdf_url",
        "source_id",
        "published_by",
        "published_at",
        "review_notes",
    },
    "posts": {
        "id",
        "recruitment_id",
        "recruitment_unit_id",
        "post_name",
        "post_code",
        "group_type",
        "pay_level",
        "job_type",
        "language_requirements",
    },
    "eligibility_results": {
        "id",
        "user_id",
        "recruitment_id",
        "post_id",
        "profile_hash",
        "is_eligible",
        "is_conditional",
        "fail_reasons",
        "pass_reasons",
        "computed_at",
    },
    "eligibility_recompute_queue": {
        "id",
        "user_id",
        "recruitment_id",
        "post_id",
        "reason",
        "status",
        "queued_at",
        "claimed_at",
        "processed_at",
        "metadata",
        "next_attempt_at",
        "attempt_count",
        "last_error",
    },
    "scrape_queue": {
        "id",
        "source_id",
        "source_url",
        "source_name",
        "raw_html",
        "raw_payload",
        "extracted_data",
        "extracted_fields",
        "confidence_score",
        "data_quality_score",
        "status",
        "duplicate_of",
        "reviewer_id",
        "reviewer_notes",
        "reviewed_at",
        "field_evidence",
        "official_source_resolved",
        "official_source_host",
        "extraction_status",
        "evidence_required",
        "scraped_at",
        "notification_document_id",
        "promoted_recruitment_id",
    },
    "notification_documents": {
        "id",
        "source_id",
        "scrape_queue_id",
        "file_url",
        "storage_path",
        "content_hash",
        "document_type",
        "created_at",
    },
    "salary_details": {
        "id",
        "post_id",
        "pay_level",
        "basic_pay_min",
        "basic_pay_max",
        "in_hand_estimate",
    },
    "extracted_field_evidence": {
        "id",
        "scrape_queue_id",
        "document_id",
        "entity_type",
        "entity_key",
        "field_name",
        "evidence_text",
        "reviewer_status",
        "reviewed_by",
        "reviewed_at",
        "reviewer_notes",
        "extraction_method",
        "extracted_value",
        "created_at",
    },
    "notification_alerts": {
        "id",
        "user_id",
        "recruitment_id",
        "alert_event_id",
        "alert_type",
        "priority",
        "is_read",
        "sent_at",
        "read_at",
        "explanation",
        "email_sent",
        "email_sent_at",
        "delivery_error",
        "source",
        "source_stage",
        "dedupe_key",
        "generated_at",
        "title",
        "body",
        "metadata",
    },
    "notification_generation_runs": {
        "id",
        "triggered_by_user_id",
        "scope",
        "dry_run",
        "run_limit",
        "candidates_count",
        "created_count",
        "skipped_count",
        "by_type",
        "started_at",
        "finished_at",
        "status",
        "error_message",
        "created_at",
    },
    "subscription_plans": {
        "id",
        "name",
        "description",
        "price_inr",
        "currency",
        "interval",
        "features",
        "sort_order",
        "is_active",
        "created_at",
        "updated_at",
    },
    "courses": {
        "id",
        "instructor_id",
        "title",
        "slug",
        "description",
        "short_description",
        "thumbnail_url",
        "preview_video_url",
        "price_inr",
        "original_price_inr",
        "level",
        "language",
        "exam_tags",
        "status",
        "total_lessons",
        "total_duration_mins",
        "avg_rating",
        "total_reviews",
        "total_enrollments",
        "commission_pct",
        "created_at",
        "updated_at",
    },
    "course_sections": {
        "id",
        "course_id",
        "title",
        "sort_order",
        "order_index",
        "is_free_preview",
    },
    "lessons": {
        "id",
        "section_id",
        "title",
        "content",
        "sort_order",
        "type",
        "order_index",
        "duration_mins",
        "is_free_preview",
        "content_url",
        "content_text",
    },
    "user_recruitment_applications": {
        "id",
        "user_id",
        "recruitment_id",
        "post_id",
        "status",
        "application_number",
        "fee_paid",
        "fee_amount",
        "documents_pending",
        "notes",
        "submitted_at",
        "clicked_apply_at",
        "updated_at",
        "created_at",
    },
    "recruitment_units": {
        "id",
        "recruitment_id",
        "organization_id",
        "unit_code",
        "unit_name",
        "location_state",
        "location_city",
        "preference_order",
        "created_at",
    },
    "vacancy_reservations": {
        "id",
        "post_id",
        "vertical_category",
        "horizontal_category",
        "vacancy_count",
        "is_backlog",
        "source_note",
        "created_at",
    },
    "disability_types": {
        "code",
        "description",
        "is_active",
    },
    "physical_requirement_types": {
        "code",
        "description",
        "is_active",
    },
    "post_disability_requirements": {
        "id",
        "post_id",
        "disability_code",
        "physical_requirement_code",
        "suitable",
        "source_note",
        "created_at",
    },
    "age_relaxation_rules": {
        "id",
        "post_id",
        "reservation_category",
        "condition_key",
        "additional_years",
        "max_age_cap",
        "cumulative",
        "source_note",
        "created_at",
    },
    "exam_patterns": {
        "id",
        "post_id",
        "stage_name",
        "section_name",
        "question_count",
        "marks",
        "duration_minutes",
        "negative_marking",
        "sort_order",
        "source_note",
        "created_at",
    },
    "skill_tests": {
        "id",
        "post_id",
        "test_type",
        "speed_requirement",
        "duration_minutes",
        "evaluation_formula",
        "source_note",
        "created_at",
    },
    "aspirant_reservations": {
        "user_id",
        "category",
        "disability_code",
        "family_income_annual",
        "ews_assets",
        "ews_certificate_available",
    },
    "aspirant_preferences": {
        "user_id",
        "languages_known",
        "preferred_language",
    },
    "education_criteria": {
        "id",
        "post_id",
        "allow_higher_qualification",
        "accepted_equivalent_qualifications",
        "raw_requirement_text",
    },
}


@pytest.mark.integration
@pytest.mark.parametrize(("table", "columns"), REQUIRED_COLUMNS.items())
def test_backend_required_schema_columns_exist(table, columns):
    if not (
        os.getenv("NEXT_PUBLIC_SUPABASE_URL")
        and os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    ):
        pytest.skip("Supabase service-role credentials are not configured")

    supabase = get_supabase_admin()
    select_list = ",".join(sorted(columns))

    try:
        supabase.table(table).select(select_list).limit(0).execute()
    except Exception as exc:  # noqa: BLE001
        raise AssertionError(
            f"{table} is missing one or more backend-required columns: {select_list}"
        ) from exc
