import os

import pytest

from app.db.supabase_client import get_supabase_admin


REQUIRED_COLUMNS = {
    "profiles": {
        "id",
        "full_name",
        "phone",
        "gender",
        "category",
        "pwbd_status",
        "domicile_state",
        "nationality",
        "ex_serviceman",
        "govt_employee",
        "dob",
        "date_of_birth",
        "service_years",
        "graduation_year",
        "target_type",
        "target_exam",
        "career_stage",
        "career_goal",
        "onboarding_step",
        "onboarding_completed",
        "is_admin",
        "is_instructor",
        "instructor_bio",
        "plan_id",
        "avatar_url",
    },
    "recruitments": {
        "id",
        "organization_id",
        "source_id",
        "slug",
        "name",
        "year",
        "status",
        "publish_status",
        "notification_date",
        "apply_start_date",
        "apply_end_date",
        "total_vacancies",
        "official_notification_url",
        "official_apply_url",
        "source_pdf_url",
        "source_id",
        "published_by",
        "published_at",
        "review_notes",
    },
    "organizations": {
        "id",
        "name",
        "type",
        "state",
        "website_url",
        "official_domain",
        "is_verified",
        "trust_tier",
        "verification_notes",
        "verified_at",
        "verified_by",
    },
    "source_registry": {
        "id",
        "organization_id",
        "source_name",
        "source_url",
        "short_code",
        "official_url",
        "notification_url",
        "parser_config",
        "scrape_config",
        "trust_config",
        "adapter_config",
        "source_type",
        "category",
        "jurisdiction",
        "state",
        "parent_org",
        "is_active",
        "is_verified",
        "is_official_source",
        "can_publish_directly",
        "discovery_only",
        "verification_status",
        "last_error",
        "last_success_at",
        "last_scraped_at",
        "last_changed_at",
        "consecutive_fails",
        "anti_bot_risk",
        "has_captcha",
        "notes",
        "added_by",
        "insecure_tls",
        "updated_at",
    },
    "scrape_runs": {
        "id",
        "source_id",
        "status",
        "started_at",
        "completed_at",
        "triggered_by",
        "triggered_by_user",
        "finished_at",
        "sources_checked",
        "items_found",
        "items_new",
        "items_duplicate",
        "error_log",
        "providers_health",
        "function_version",
    },
    "posts": {
        "id",
        "recruitment_id",
        "recruitment_unit_id",
        "post_name",
        "post_code",
        "group_type",
        "pay_level",
        "job_type",
        "language_requirements",
    },
    "age_criteria": {
        "id",
        "post_id",
        "min_age",
        "max_age",
        "cutoff_date",
    },
    "eligibility_results": {
        "id",
        "user_id",
        "recruitment_id",
        "post_id",
        "profile_hash",
        "is_eligible",
        "is_conditional",
        "fail_reasons",
        "pass_reasons",
        "computed_at",
    },
    "eligibility_recompute_queue": {
        "id",
        "user_id",
        "recruitment_id",
        "post_id",
        "reason",
        "status",
        "queued_at",
        "claimed_at",
        "processed_at",
        "metadata",
        "next_attempt_at",
        "attempt_count",
        "last_error",
    },
    "scrape_queue": {
        "id",
        "source_id",
        "source_url",
        "source_name",
        "raw_html",
        "raw_payload",
        "extracted_data",
        "extracted_fields",
        "confidence_score",
        "data_quality_score",
        "status",
        "duplicate_of",
        "duplicate_recruitment_id",
        "reviewer_id",
        "reviewer_notes",
        "reviewed_at",
        "field_evidence",
        "official_source_resolved",
        "official_source_host",
        "extraction_status",
        "evidence_required",
        "scraped_at",
        "notification_document_id",
        "promoted_recruitment_id",
    },
    "notification_documents": {
        "id",
        "source_id",
        "scrape_run_id",
        "scrape_queue_id",
        "file_url",
        "source_url",
        "final_url",
        "storage_path",
        "content_hash",
        "document_type",
        "fetched_at",
        "http_status",
        "etag",
        "last_modified",
        "raw_text",
        "metadata",
        "created_at",
    },
    "salary_details": {
        "id",
        "post_id",
        "pay_level",
        "basic_pay_min",
        "basic_pay_max",
        "in_hand_estimate",
    },
    "extracted_field_evidence": {
        "id",
        "scrape_queue_id",
        "document_id",
        "entity_type",
        "entity_key",
        "field_name",
        "evidence_text",
        "reviewer_status",
        "reviewed_by",
        "reviewed_at",
        "reviewer_notes",
        "extraction_method",
        "extracted_value",
        "corrected_value",
        "page_number",
        "char_start",
        "char_end",
        "model",
        "confidence",
        "source_page",
        "source_bbox",
        "alignment_status",
        "created_at",
    },
    "notification_alerts": {
        "id",
        "user_id",
        "recruitment_id",
        "alert_event_id",
        "alert_type",
        "priority",
        "is_read",
        "sent_at",
        "read_at",
        "explanation",
        "email_sent",
        "email_sent_at",
        "delivery_error",
        "source",
        "source_stage",
        "dedupe_key",
        "generated_at",
        "title",
        "body",
        "metadata",
    },
    "notification_generation_runs": {
        "id",
        "triggered_by_user_id",
        "scope",
        "dry_run",
        "run_limit",
        "candidates_count",
        "created_count",
        "skipped_count",
        "by_type",
        "started_at",
        "finished_at",
        "status",
        "error_message",
        "created_at",
    },
    "notification_preferences": {
        "user_id",
        "in_app_enabled",
        "email_enabled",
        "in_app_types_disabled",
        "email_types_disabled",
        "event_types_muted",
        "digest_preference",
        "quiet_hours_start",
        "quiet_hours_end",
        "min_priority_in_app",
        "min_priority_email",
        "deadline_reminder_windows",
        "updated_at",
    },
    "candidate_field_registry": {
        "field_key",
        "canonical_label",
        "user_facing_label",
        "data_type",
        "profile_group",
        "profile_table",
        "profile_column",
        "question_template",
        "allowed_values",
        "synonyms",
        "is_active",
    },
    "recruitment_question_requirements": {
        "id",
        "recruitment_id",
        "post_id",
        "field_key",
        "requirement_type",
        "required_for",
        "priority",
        "question_text",
        "rule_operator",
        "rule_value",
        "is_knockout",
        "reviewer_status",
    },
    "funnel_sessions": {
        "id",
        "user_id",
        "anonymous_id",
        "recruitment_id",
        "post_id",
        "intent",
        "utm",
        "status",
        "created_at",
        "updated_at",
    },
    "onboarding_sessions": {
        "id",
        "user_id",
        "funnel_session_id",
        "mode",
        "current_field_key",
        "missing_fields",
        "completed_fields",
        "status",
    },
    "onboarding_answers": {
        "id",
        "session_id",
        "user_id",
        "field_key",
        "answer_value",
        "normalized_value",
        "source",
        "confidence",
        "needs_review",
    },
    "ai_action_policies": {
        "id",
        "action",
        "mode",
        "reason",
        "is_active",
        "created_at",
        "updated_at",
    },
    "chat_sessions": {
        "id",
        "user_id",
        "title",
        "messages",
        "metadata",
        "created_at",
        "updated_at",
    },
    "subscription_plans": {
        "id",
        "plan_code",
        "name",
        "description",
        "price_inr",
        "currency",
        "interval",
        "features",
        "sort_order",
        "is_active",
        "created_at",
        "updated_at",
    },
    "user_subscriptions": {
        "id",
        "user_id",
        "plan_id",
        "status",
        "razorpay_order_id",
        "razorpay_payment_id",
        "amount_paid_inr",
        "currency",
        "current_period_start",
        "current_period_end",
        "cancelled_at",
        "created_at",
        "updated_at",
    },
    "payment_history": {
        "id",
        "user_id",
        "subscription_id",
        "plan_id",
        "razorpay_order_id",
        "razorpay_payment_id",
        "amount_inr",
        "currency",
        "status",
        "method",
        "source",
        "event",
        "raw_event",
        "created_at",
    },
    "courses": {
        "id",
        "instructor_id",
        "title",
        "slug",
        "description",
        "short_description",
        "thumbnail_url",
        "preview_video_url",
        "price_inr",
        "original_price_inr",
        "level",
        "language",
        "exam_tags",
        "status",
        "total_lessons",
        "total_duration_mins",
        "avg_rating",
        "total_reviews",
        "total_enrollments",
        "commission_pct",
        "created_at",
        "updated_at",
    },
    "course_sections": {
        "id",
        "course_id",
        "title",
        "sort_order",
        "order_index",
        "is_free_preview",
    },
    "lessons": {
        "id",
        "section_id",
        "title",
        "content",
        "sort_order",
        "type",
        "order_index",
        "duration_mins",
        "is_free_preview",
        "content_url",
        "content_text",
    },
    "reviews": {
        "id",
        "user_id",
        "course_id",
        "rating",
        "comment",
        "body",
        "created_at",
        "updated_at",
    },
    "enrollments": {
        "id",
        "user_id",
        "course_id",
        "status",
        "amount_paid_inr",
        "razorpay_order_id",
        "razorpay_payment_id",
        "enrolled_at",
        "completed_at",
    },
    "lesson_progress": {
        "id",
        "user_id",
        "lesson_id",
        "course_id",
        "completed",
        "completed_at",
        "watch_seconds",
    },
    "instructor_payouts": {
        "id",
        "instructor_id",
        "amount_inr",
        "status",
        "period_start",
        "period_end",
        "razorpay_payout_id",
        "created_at",
    },
    "study_plans": {
        "id",
        "user_id",
        "title",
        "status",
        "target_exam",
        "weekly_hours_goal",
        "metadata",
        "updated_at",
    },
    "study_tasks": {
        "id",
        "plan_id",
        "user_id",
        "title",
        "day_label",
        "subject",
        "topic",
        "task_type",
        "duration_mins",
        "planned_minutes",
        "scheduled_date",
        "status",
        "completed_at",
        "updated_at",
    },
    "study_sessions": {
        "id",
        "plan_id",
        "user_id",
        "starts_at",
        "ends_at",
        "started_at",
        "ended_at",
        "duration_minutes",
        "duration_mins",
        "session_type",
        "subject",
        "topic",
        "notes",
    },
    "mock_tests": {
        "id",
        "user_id",
        "plan_id",
        "exam_name",
        "test_name",
        "total_questions",
        "total_marks",
        "scored_marks",
        "correct_answers",
        "wrong_answers",
        "duration_mins",
        "attempted_at",
    },
    "mock_subject_breakdowns": {
        "id",
        "mock_test_id",
        "subject",
        "total_questions",
        "correct_answers",
        "wrong_answers",
        "marks",
        "accuracy",
    },
    "forum_categories": {
        "id",
        "name",
        "slug",
        "description",
        "exam_tag",
        "post_count",
        "order_index",
        "is_active",
    },
    "forum_posts": {
        "id",
        "category_id",
        "user_id",
        "title",
        "body",
        "slug",
        "reply_count",
        "upvote_count",
        "is_locked",
        "exam_tags",
        "status",
        "search_vector",
    },
    "forum_reports": {
        "id",
        "reporter_id",
        "target_type",
        "post_id",
        "comment_id",
        "reason",
        "severity",
        "status",
        "created_at",
    },
    "user_events": {
        "id",
        "user_id",
        "event_name",
        "recruitment_id",
        "metadata",
        "occurred_at",
    },
    "form_submissions": {
        "id",
        "user_id",
        "recruitment_id",
        "status",
        "payload",
        "submitted_at",
    },
    "recruitment_events": {
        "id",
        "recruitment_id",
        "event_type",
        "event_date",
        "source_id",
        "scrape_queue_id",
        "payload",
    },
    "user_recruitment_applications": {
        "id",
        "user_id",
        "recruitment_id",
        "post_id",
        "status",
        "application_number",
        "fee_paid",
        "fee_amount",
        "documents_pending",
        "notes",
        "submitted_at",
        "clicked_apply_at",
        "updated_at",
        "created_at",
    },
    "recruitment_units": {
        "id",
        "recruitment_id",
        "organization_id",
        "unit_code",
        "unit_name",
        "location_state",
        "location_city",
        "preference_order",
        "created_at",
    },
    "vacancy_reservations": {
        "id",
        "post_id",
        "vertical_category",
        "horizontal_category",
        "vacancy_count",
        "is_backlog",
        "source_note",
        "created_at",
    },
    "disability_types": {
        "code",
        "description",
        "is_active",
    },
    "physical_requirement_types": {
        "code",
        "description",
        "is_active",
    },
    "post_disability_requirements": {
        "id",
        "post_id",
        "disability_code",
        "physical_requirement_code",
        "suitable",
        "source_note",
        "created_at",
    },
    "age_relaxation_rules": {
        "id",
        "post_id",
        "reservation_category",
        "condition_key",
        "additional_years",
        "max_age_cap",
        "cumulative",
        "source_note",
        "created_at",
    },
    "exam_patterns": {
        "id",
        "post_id",
        "stage_name",
        "section_name",
        "question_count",
        "marks",
        "duration_minutes",
        "negative_marking",
        "sort_order",
        "source_note",
        "created_at",
    },
    "skill_tests": {
        "id",
        "post_id",
        "test_type",
        "speed_requirement",
        "duration_minutes",
        "evaluation_formula",
        "source_note",
        "created_at",
    },
    "aspirant_reservations": {
        "user_id",
        "category",
        "disability_code",
        "family_income_annual",
        "ews_assets",
        "ews_certificate_available",
    },
    "aspirant_preferences": {
        "user_id",
        "languages_known",
        "preferred_language",
    },
    "education_criteria": {
        "id",
        "post_id",
        "min_qualification_level",
        "allowed_disciplines",
        "allow_higher_qualification",
        "accepted_equivalent_qualifications",
        "raw_requirement_text",
    },
}


@pytest.mark.integration
@pytest.mark.parametrize(("table", "columns"), REQUIRED_COLUMNS.items())
def test_backend_required_schema_columns_exist(table, columns):
    if not (
        os.getenv("NEXT_PUBLIC_SUPABASE_URL")
        and os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    ):
        pytest.skip("Supabase service-role credentials are not configured")

    supabase = get_supabase_admin()
    select_list = ",".join(sorted(columns))

    try:
        supabase.table(table).select(select_list).limit(0).execute()
    except Exception as exc:  # noqa: BLE001
        raise AssertionError(
            f"{table} is missing one or more backend-required columns: {select_list}"
        ) from exc
