create index if not exists idx_recruitments_status on public.recruitments(status);
create index if not exists idx_recruitments_publish_status on public.recruitments(publish_status);
create index if not exists idx_recruitments_apply_end_date on public.recruitments(apply_end_date);
create index if not exists idx_posts_recruitment_id on public.posts(recruitment_id);
create index if not exists idx_elig_results_user_recruit_post on public.eligibility_results(user_id, recruitment_id, post_id);
create index if not exists idx_elig_results_profile_hash on public.eligibility_results(profile_hash);
create index if not exists idx_elig_queue_status_queued_at on public.eligibility_recompute_queue(status, queued_at);
create index if not exists idx_scrape_queue_status on public.scrape_queue(status);
create index if not exists idx_scrape_queue_scraped_at on public.scrape_queue(scraped_at);
create index if not exists idx_scrape_queue_reviewed_at on public.scrape_queue(reviewed_at);
create index if not exists idx_scrape_queue_data_quality on public.scrape_queue(data_quality_score);
create index if not exists idx_evidence_document_id on public.extracted_field_evidence(document_id);
create index if not exists idx_evidence_scrape_queue_id on public.extracted_field_evidence(scrape_queue_id);
create index if not exists idx_evidence_field_name on public.extracted_field_evidence(field_name);
create index if not exists idx_evidence_reviewer_status on public.extracted_field_evidence(reviewer_status);
create unique index if not exists uq_evidence_entity_scoped on public.extracted_field_evidence(scrape_queue_id, entity_type, coalesce(entity_key, ''), field_name);
create index if not exists idx_notification_alerts_user_read_sent on public.notification_alerts(user_id, is_read, sent_at desc);
create unique index if not exists uq_tracked_recruitments_user_recruitment on public.tracked_recruitments(user_id, recruitment_id);
create index if not exists idx_source_registry_active_type_state on public.source_registry(is_active, source_type, state);
create index if not exists idx_user_recruitment_applications_user_recruitment on public.user_recruitment_applications(user_id, recruitment_id);
